# Site settings
title: NO Developers Left Behind
email: jacqnelson@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A weekly study group dedicated to helping people learn how to build websites from scratch.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://spaceotterinspace.com" # the base hostname & protocol for your site
twitter_username: spaceotterin
github_username:  spaceotterinspace

# Build settings
markdown: kramdown
